"use client";
import { useState } from 'react';
import Link from 'next/link';
import type { ProfitReport } from '@/lib/profit-report';
const money = (v: number) => v.toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
const labels: Record<string,string> = {drug:'ยา',supply:'เวชภัณฑ์',lab:'แล็บ',lab_external:'แล็บภายนอก',procedure:'หัตถการ',service:'บริการ',doctor_fee:'ค่าตรวจ',package:'คอร์สบริการ',other:'อื่นๆ'};
export default function ProfitPanel({data, start, end}: {data: ProfitReport; start: string; end: string}) {
    const [extraCost,setExtraCost] = useState('');
    const [operating,setOperating] = useState('');
    const [revenue,setRevenue] = useState('');
    const ready = [extraCost,operating,revenue].every(v=>v.trim()!=='' && Number.isFinite(Number(v)) && Number(v)>=0);
    const toCents = (v: number|string) => Math.round(Number(v)*100);
    const estimate = ready ? (toCents(revenue)-toCents(data.cogs)-toCents(data.df)-toCents(extraCost)-toCents(operating))/100 : null;
    function download() {
        const rows = [['รายงานกำไร–ขาดทุน / ต้นทุน (ข้อมูลยังไม่ครบ)'],['ช่วงวันที่',start,end],['ขอบเขต','ทั้งคลินิก'],['ยอดบิลสุทธิทั่วไป',data.regularSales],['นิรนามชำระแล้ว',data.anonymousSales],['ยอดรับเงินจริงสุทธิ',data.cashReceived],['ต้นทุนที่บันทึก',data.cogs],['ค่าแพทย์ที่บันทึก',data.df],['รายจ่ายที่บันทึก (ยังไม่จัดประเภททางบัญชี)',data.expenses],['กำไรสุทธิ','ยังคำนวณไม่ได้'],['รายการต้นทุนที่ต้องตรวจสอบ',data.unverifiedCosts],['ต้นทุนแยกประเภท','จำนวน','ต้นทุนที่บันทึก','ค่าแพทย์'],...data.costs.map(r=>[labels[r.type]||r.type,r.count,r.cost,r.df])];
        const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"').join(',')).join('\n');
        const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`profit-${start}-${end}.csv`;a.click();URL.revokeObjectURL(url);
    }
    return <section className="space-y-5">
        <div className="gonix-card-premium p-5 sm:p-6">
            <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold text-slate-800">กำไร–ขาดทุน / ต้นทุน</h2><p className="mt-1 text-sm text-slate-600">ภาพรวมทั้งคลินิก รวมใบเสร็จนิรนาม · {start} ถึง {end}</p></div><button onClick={download} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm text-slate-700">ส่งออก CSV</button></div>
            <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                {([['ยอดบิลสุทธิ + นิรนาม',data.sales],['ต้นทุนที่บันทึก',data.cogs],['ค่าแพทย์ที่บันทึก',data.df],['รายจ่ายที่บันทึก',data.expenses]] as const).map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200/70 bg-white/70 p-4"><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums text-slate-900">฿{money(value)}</p></div>)}
            </div>
            <p className="mt-4 text-sm leading-relaxed text-slate-600">ยอดบิลใช้ราคาหลังส่วนลดตามวันออกบิล ตัดบิลร่าง ยกเลิก และคืนเงินทั้งใบ; นิรนามใช้วันรับเงิน ยอดนี้ยังไม่ใช่รายได้ที่รับรู้ทางบัญชีของคอร์สหรือเงินมัดจำ</p>
        </div>
        <div className="grid gap-5 xl:grid-cols-[1.3fr_1fr]">
            <div className="gonix-card-premium p-5 sm:p-6"><h3 className="font-semibold text-lg text-slate-800">องค์ประกอบกำไร–ขาดทุน</h3><dl className="mt-3 divide-y divide-slate-100">
                {([['ยอดบิลสุทธิทั่วไป',data.regularSales],['ใบเสร็จนิรนามชำระแล้ว',data.anonymousSales],['ต้นทุนยา / สินค้า / บริการที่บันทึก',data.cogs],['ค่าแพทย์ที่บันทึก',data.df],['รายจ่ายทุกช่องทางที่บันทึก',data.expenses]] as const).map(([label,value])=><div key={label} className="flex justify-between gap-4 py-3 text-sm"><dt className="text-slate-600">{label}</dt><dd className="font-medium tabular-nums text-slate-900">฿{money(value)}</dd></div>)}
                <div className="flex justify-between gap-4 py-4"><dt className="font-semibold">กำไรสุทธิ</dt><dd className="text-sm font-medium text-slate-600">ยังคำนวณไม่ได้ — ข้อมูลไม่ครบ</dd></div>
            </dl><p className="text-sm leading-relaxed text-slate-500">รายจ่ายยังไม่ได้แยกสินทรัพย์ ซื้อสต็อก และค่าใช้จ่ายดำเนินงาน จึงยังไม่นำมาหักรวมกับต้นทุนสินค้า เพื่อป้องกันการนับซ้ำ</p><div className="mt-4 rounded-xl bg-blue-50 p-4 text-sm text-blue-800">รับเงินจริงสุทธิในช่วงนี้ ฿{money(data.cashReceived)}<span className="block mt-1 text-blue-700">รวมรับชำระบิลเก่าและหักเงินคืน แสดงแยกจากกำไร</span></div></div>
            <div className="gonix-card-premium p-5 sm:p-6"><h3 className="font-semibold text-lg text-slate-800">ข้อมูลที่ต้องตรวจสอบ</h3><ul className="mt-4 space-y-3 text-sm leading-relaxed text-slate-600"><li>ต้นทุนเป็นศูนย์ / ยังไม่บันทึก: <strong>{data.unverifiedCosts} รายการ</strong></li><li>ค่าแพทย์เป็นศูนย์ / ยังไม่ยืนยัน: <strong>{data.unverifiedDf} รายการ</strong></li><li>บิลที่ไม่มีรายละเอียดรายการ: <strong>{data.invoicesWithoutItems} ใบ</strong></li><li>ใบเสร็จนิรนามที่ยังไม่เชื่อมต้นทุน: <strong>{data.anonymousCount} ใบ</strong></li><li>รายการขายคอร์สที่ต้องทบทวนการรับรู้รายได้: <strong>{data.packageCount} รายการ</strong></li><li>ยังไม่ยืนยันความครบถ้วนของเงินเดือน ค่าเช่า ค่าน้ำไฟ ค่าธรรมเนียม คอมมิชชัน ค่าเสื่อม และภาษี</li></ul><p className="mt-4 text-sm text-slate-500">ยอดต้นทุน 0.00 หมายถึงยอดที่พบในระบบ ไม่ใช่การยืนยันว่าไม่มีต้นทุน</p><div className="mt-5 flex flex-wrap gap-3 text-sm text-blue-700"><Link href="/dashboard/inventory">ดูคลังสินค้า →</Link><Link href="/dashboard/finance">ดูการเงิน →</Link></div></div>
        </div>
        <div className="gonix-card-premium overflow-hidden"><h3 className="px-5 py-4 text-lg font-semibold">ต้นทุนตามประเภท</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{['ประเภท','รายการ','ต้นทุนที่บันทึก','ค่าแพทย์','ต้องตรวจสอบต้นทุน'].map(h=><th key={h} className="px-5 py-3 text-left font-medium">{h}</th>)}</tr></thead><tbody>{data.costs.map(r=><tr key={r.type} className="border-t border-slate-100"><td className="px-5 py-3">{labels[r.type]||r.type}</td><td className="px-5 py-3">{r.count}</td><td className="px-5 py-3 tabular-nums">฿{money(r.cost)}</td><td className="px-5 py-3 tabular-nums">฿{money(r.df)}</td><td className="px-5 py-3">{r.unverified}</td></tr>)}</tbody></table>{data.costs.length===0&&<p className="p-5 text-slate-500">ไม่มีรายการในช่วงวันที่เลือก</p>}</div></div>
        <details className="gonix-card-premium p-5"><summary className="cursor-pointer font-semibold">รายจ่ายแยกหมวด ({data.expenseGroups.length})</summary><div className="mt-3 space-y-2">{data.expenseGroups.map(e=><div key={e.category} className="flex justify-between text-sm"><span>{e.category}</span><span>฿{money(e.amount)}</span></div>)}{!data.expenseGroups.length&&<p className="text-sm text-slate-500">ยังไม่มีรายจ่ายบันทึกในช่วงนี้</p>}</div></details>
        <details className="gonix-card-premium p-5"><summary className="cursor-pointer font-semibold">ทดลองประมาณการกำไร–ขาดทุน</summary><p className="mt-3 text-sm text-slate-500">กรอกยอดที่ตรวจสอบแล้วเพื่อทดลองคำนวณ ตัวเลขส่วนนี้ไม่บันทึกบัญชีและไม่รวมใน CSV</p><div className="mt-4 grid gap-4 md:grid-cols-3">{([{label:'รายได้ที่รับรู้ในช่วงนี้ (บาท)',value:revenue,set:setRevenue},{label:'ต้นทุนและค่าแพทย์ที่ต้องเพิ่ม (บาท)',value:extraCost,set:setExtraCost},{label:'ค่าใช้จ่ายดำเนินงานรวม (บาท)',value:operating,set:setOperating}]).map(f=><label key={f.label} className="text-sm text-slate-600">{f.label}<input type="number" min="0" step="0.01" value={f.value} onChange={e=>f.set(e.target.value)} placeholder="กรอกยอด รวม 0 หากไม่มี" className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3"/></label>)}</div><p className="mt-3 text-sm text-slate-500">หักต้นทุนและค่าแพทย์ที่บันทึกแล้ว ฿{money((toCents(data.cogs)+toCents(data.df))/100)} เพิ่มให้อัตโนมัติ ค่าใช้จ่ายดำเนินงานให้กรอกยอดรวมที่ตรวจแล้ว ไม่รวมซื้อสต็อกหรือสินทรัพย์ซ้ำ</p><p className="mt-4 text-lg font-semibold">{estimate===null?'กรอกให้ครบเพื่อดูผลประมาณการ':`${estimate<0?'ขาดทุน':'กำไร'}ประมาณการ ฿${money(Math.abs(estimate))}`}</p></details>
    </section>;
}
