const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');const vm=require('node:vm');
function compile(file,require){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports:m.exports,require});return m.exports}
const money=compile('lib/overview-money.ts');
test('mixed methods sum cents exactly and refund reduces net receipts',()=>{assert.equal(money.sumMoney([.1,.2]),.3);assert.equal(money.sumMoney([500,1500,-200]),1800)});
test('deposit does not count full bill as received; outstanding excludes excess paid',()=>assert.equal(money.outstandingMoney([{total_amount:5000,paid_amount:2000},{total_amount:100,paid_amount:110}]),3000));
async function render(allowed=true,fail=false){const calls=[];const db={from(table){let offset=0;const q={};for(const method of ['select','eq','neq','gte','lt','not','order','range'])q[method]=(...args)=>{calls.push([table,method,...args]);if(method==='range')offset=args[0];return q};q.then=resolve=>Promise.resolve({error:fail?{}:null,data:table==='payment_logs'?(offset===0?Array.from({length:500},()=>({amount:1,note:null,deposit_type:'none'})):[{amount:2000,note:'มัดจำ — ค้าง 3000 บาท',deposit_type:'none'}]):[{total_amount:5000,paid_amount:2000}]}).then(resolve);return q}};
const component=compile('app/(dashboard)/dashboard/overview/finance-summary.tsx',n=>n==='react/jsx-runtime'?{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})}:n.includes('supabase/server')?{createClient:async()=>db}:n.includes('auth/permissions')?{getEffectivePermissionsForUser:async()=>({clinicId:'test-clinic',permissions:{'finance.view':allowed}})}:n.includes('overview-money')?money:{});
const result=await component.default({today:'2026-09-13'});return {result,calls,text:JSON.stringify(result)}}
test('financial data never queried without permission',async()=>{const r=await render(false);assert.equal(r.result,null);assert.equal(r.calls.length,0)});
test('fetches more than 500 payments and uses Thai midnight, clinic scope, void exclusion',async()=>{const r=await render();assert.match(r.text,/2,500.00/);assert.match(r.text,/2,000.00/);assert.match(r.text,/3,000.00/);assert.ok(r.calls.some(c=>c[1]==='range'&&c[2]===500));assert.ok(r.calls.some(c=>c[1]==='gte'&&c[3]==='2026-09-13T00:00:00+07:00'));assert.ok(r.calls.some(c=>c[1]==='lt'&&c[3]==='2026-09-13T17:00:00.000Z'));assert.ok(r.calls.some(c=>c[1]==='eq'&&c[2]==='clinic_id'&&c[3]==='test-clinic'))});
test('failure shows error rather than financial zero',async()=>{const r=await render(true,true);assert.match(r.text,/โหลดข้อมูลการเงินไม่สำเร็จ/);assert.doesNotMatch(r.text,/฿0.00/)});
