-- ============================================================
-- 012_icd10_seed_from_clinic.sql
-- Description: Inserts clinic-specific ICD-10 codes from GAS
-- into the icd10 table. Covers common diagnoses used in
-- Thai primary care / OPD clinics.
-- ============================================================

INSERT INTO icd10 (code, description_th, description_en, category) VALUES
-- Infectious / Gastrointestinal
('A009', 'อหิวาตกโรค', 'Cholera, unspecified', 'Infectious'),
('A090', 'ท้องร่วง', 'Gastroenteritis and colitis of infectious origin', 'Digestive'),
('A099', 'อุจจาระร่วง', 'Gastroenteritis and colitis of unspecified origin', 'Digestive'),
('A059', 'อาหารเป็นพิษจากเชื้อแบคทีเรีย', 'Bacterial food-borne intoxication, unspecified', 'Infectious'),
('A039', 'โรคบิดจากเชื้อชิเกลลา', 'Shigellosis, unspecified', 'Infectious'),
-- STI
('A549', 'หนองใน', 'Gonococcal infection, unspecified', 'Infectious'),
('N341', 'หนองในเทียม', 'Nonspecific urethritis', 'Infectious'),
('A539', 'ซิฟิลิส', 'Syphilis, unspecified', 'Infectious'),
('A57', 'แผลริมอ่อน', 'Chancroid', 'Infectious'),
('A630', 'หูดหงอนไก่', 'Anogenital (venereal) warts', 'Infectious'),
('A609', 'เริมที่อวัยวะเพศ', 'Anogenital herpesviral infection, unspecified', 'Infectious'),
('B009', 'เริม', 'Herpesviral infection, unspecified', 'Infectious'),
('A55', 'ฝีมะม่วง', 'Chlamydial lymphogranuloma (venereum)', 'Infectious'),
-- Viral / Skin infections
('B088', 'โรคมือ เท้า ปาก', 'Other specified viral infections', 'Infectious'),
('B029', 'งูสวัด', 'Zoster without complication', 'Infectious'),
('B059', 'หัด', 'Measles without complication', 'Infectious'),
('B069', 'หัดเยอรมัน', 'Rubella without complication', 'Infectious'),
('B07', 'หูด ตาปลา', 'Viral warts', 'Infectious'),
('B24', 'เอดส์', 'Unspecified human immunodeficiency virus [HIV] disease', 'Infectious'),
('A920', 'ไข้ชิกุนคุนยา', 'Chikungunya virus disease', 'Infectious'),
('B360', 'เกลื้อน', 'Pityriasis versicolor', 'Skin'),
-- Malaria
('B519', 'มาลาเรีย PV ไม่มีภาวะแทรกซ้อน', 'Plasmodium vivax malaria without complication', 'Infectious'),
('B54', 'มาลาเรียไม่ระบุเชื้อ', 'Unspecified malaria', 'Infectious'),
('B538', 'มาลาเรียหลายเชื้อ', 'Other parasitologically confirmed malaria', 'Infectious'),
('B509', 'มาลาเรีย PF ไม่มีภาวะแทรกซ้อน', 'Plasmodium falciparum malaria, unspecified', 'Infectious'),
('B86', 'หิด', 'Scabies', 'Infectious'),
-- Respiratory
('J00', 'ไข้หวัด', 'Acute nasopharyngitis (common cold)', 'Respiratory'),
('J019', 'โพรงอากาศอักเสบเฉียบพลัน (ไซนัส)', 'Acute sinusitis, unspecified', 'Respiratory'),
('J029', 'คอหอยอักเสบเฉียบพลัน', 'Acute pharyngitis, unspecified', 'Respiratory'),
('J039', 'ทอนซิลอักเสบเฉียบพลัน', 'Acute tonsillitis, unspecified', 'Respiratory'),
('J069', 'ติดเชื้อทางเดินหายใจส่วนบน (URI)', 'Acute upper respiratory infection, unspecified', 'Respiratory'),
('J189', 'ปอดบวม', 'Pneumonia, unspecified', 'Respiratory'),
('J209', 'หลอดลมอักเสบเฉียบพลัน', 'Acute bronchitis, unspecified', 'Respiratory'),
('J219', 'หลอดลมฝอยอักเสบเฉียบพลัน', 'Acute bronchiolitis, unspecified', 'Respiratory'),
('J304', 'เยื่อจมูกอักเสบจากภูมิแพ้', 'Allergic rhinitis, unspecified', 'Respiratory'),
('J310', 'เยื่อจมูกอักเสบเรื้อรัง', 'Chronic rhinitis', 'Respiratory'),
('J312', 'คอหอยอักเสบเรื้อรัง', 'Chronic pharyngitis', 'Respiratory'),
('J329', 'โพรงอากาศอักเสบเรื้อรัง', 'Chronic sinusitis, unspecified', 'Respiratory'),
('J350', 'ทอนซิลอักเสบเรื้อรัง', 'Chronic tonsillitis', 'Respiratory'),
('J40', 'หลอดลมอักเสบ (ไม่ระบุ)', 'Bronchitis, not specified as acute or chronic', 'Respiratory'),
('J449', 'โรคปอดอุดกั้นเรื้อรัง (COPD)', 'Chronic obstructive pulmonary disease, unspecified', 'Respiratory'),
('J46', 'โรคหืดในภาวะหอบไม่หยุด', 'Status asthmaticus', 'Respiratory'),
('J459', 'โรคหืด', 'Asthma, unspecified', 'Respiratory'),
-- Musculoskeletal
('M545', 'ปวดหลังส่วนล่าง', 'Low back pain', 'Musculoskeletal'),
('M549', 'ปวดหลัง', 'Dorsalgia, unspecified', 'Musculoskeletal'),
('S861', 'กล้ามเนื้อน่องฉีกขาด', 'Injury of calf muscle', 'Injury'),
('M7910', 'ปวดกล้ามเนื้อ หลายที่', 'Myalgia: multiple sites', 'Musculoskeletal'),
('M7911', 'ปวดกล้ามเนื้อ หัวไหล่ บ่า', 'Myalgia: shoulder region', 'Musculoskeletal'),
('M7912', 'ปวดกล้ามเนื้อ ข้อศอก แขนท่อนบน', 'Myalgia: upper arm', 'Musculoskeletal'),
('M7913', 'ปวดกล้ามเนื้อ ข้อมือ แขนท่อนล่าง', 'Myalgia: forearm', 'Musculoskeletal'),
('M7914', 'ปวดกล้ามเนื้อ มือ', 'Myalgia: hand', 'Musculoskeletal'),
('M7915', 'ปวดกล้ามเนื้อ สะโพก ต้นขา', 'Myalgia: pelvic region and thigh', 'Musculoskeletal'),
('M7916', 'ปวดกล้ามเนื้อ เข่า ขาส่วนใต้เข่า', 'Myalgia: lower leg', 'Musculoskeletal'),
('M7917', 'ปวดกล้ามเนื้อ ข้อเท้า เท้า', 'Myalgia: ankle and foot', 'Musculoskeletal'),
('M7918', 'ปวดกล้ามเนื้อ คอ ลำตัว ชายโครง', 'Myalgia: other site', 'Musculoskeletal'),
('M069', 'รูมาตอยด์', 'Rheumatoid arthritis, unspecified', 'Musculoskeletal'),
('M109', 'เก๊าท์', 'Gout, unspecified', 'Musculoskeletal'),
('M179', 'ข้อเข่าเสื่อม', 'Gonarthrosis, unspecified', 'Musculoskeletal'),
('M542', 'ปวดคอ', 'Cervicalgia', 'Musculoskeletal'),
('M609', 'กล้ามเนื้ออักเสบ', 'Myositis, unspecified', 'Musculoskeletal'),
('M624', 'ตระคริว', 'Contracture of muscle', 'Musculoskeletal'),
('M626', 'กล้ามเนื้อเคล็ด', 'Muscle strain', 'Musculoskeletal'),
('M771', 'ปวดฝ่าเท้า (รองช้ำ)', 'Lateral epicondylitis', 'Musculoskeletal'),
-- Symptoms & Signs
('R51', 'ปวดศีรษะ', 'Headache', 'Symptoms'),
('R509', 'ไข้', 'Fever, unspecified', 'Symptoms'),
('R05', 'ไอ', 'Cough', 'Symptoms'),
('R070', 'เจ็บคอ', 'Pain in throat', 'Symptoms'),
('R42', 'วิงเวียน', 'Dizziness and giddiness', 'Symptoms'),
('R11', 'คลื่นไส้อาเจียน', 'Nausea and vomiting', 'Symptoms'),
('R14', 'ท้องอืด', 'Flatulence and related conditions', 'Symptoms'),
('R000', 'หัวใจเต้นเร็ว', 'Tachycardia, unspecified', 'Symptoms'),
('R001', 'หัวใจเต้นช้า', 'Bradycardia, unspecified', 'Symptoms'),
('R002', 'ใจสั่น', 'Palpitations', 'Symptoms'),
('R030', 'ความดันโลหิตสูง (วัดพบ)', 'Elevated blood pressure reading', 'Symptoms'),
('R031', 'ความดันโลหิตต่ำ (วัดพบ)', 'Nonspecific low blood pressure reading', 'Symptoms'),
('R040', 'เลือดกำเดา', 'Epistaxis', 'Symptoms'),
('R042', 'ไอเป็นเลือด', 'Haemoptysis', 'Symptoms'),
('R060', 'หายใจลำบาก', 'Dyspnoea', 'Symptoms'),
('R064', 'หายใจเร็วผิดปกติ (ทางจิต)', 'Hyperventilation', 'Symptoms'),
('R066', 'สะอึก', 'Hiccough', 'Symptoms'),
('R067', 'จาม', 'Sneezing', 'Symptoms'),
('R074', 'เจ็บหน้าอก', 'Chest pain, unspecified', 'Symptoms'),
('R12', 'แสบร้อนหน้าอก', 'Heartburn', 'Symptoms'),
('R17', 'ดีซ่าน', 'Unspecified jaundice', 'Symptoms'),
('R21', 'ผื่น', 'Rash and other nonspecific skin eruption', 'Symptoms'),
('R252', 'ตะคริว', 'Cramp and spasm', 'Symptoms'),
('R300', 'ปัสสาวะขัด', 'Dysuria', 'Symptoms'),
('R31', 'ปัสสาวะเป็นเลือด', 'Unspecified haematuria', 'Symptoms'),
('R33', 'ปัสสาวะไม่ออก', 'Retention of urine', 'Symptoms'),
('R53', 'เหนื่อยอ่อนเพลีย', 'Malaise and fatigue', 'Symptoms'),
('R55', 'เป็นลมหมดสติ', 'Syncope and collapse', 'Symptoms'),
('R560', 'การชักจากไข้สูง', 'Febrile convulsions', 'Symptoms'),
('R630', 'เบื่ออาหาร', 'Anorexia', 'Symptoms'),
('R739', 'น้ำตาลในเลือดสูง', 'Hyperglycaemia, unspecified', 'Symptoms'),
-- Digestive
('K219', 'กรดไหลย้อน', 'Gastro-oesophageal reflux disease', 'Digestive'),
('K259', 'แผลกระเพาะอาหาร', 'Gastric ulcer, unspecified', 'Digestive'),
('K297', 'กระเพาะอาหารอักเสบ', 'Gastritis, unspecified', 'Digestive'),
('K30', 'อาหารไม่ย่อย', 'Dyspepsia', 'Digestive'),
('K358', 'ไส้ติ่งอักเสบเฉียบพลัน', 'Acute appendicitis', 'Digestive'),
('K409', 'ไส้เลื่อนขาหนีบ', 'Inguinal hernia', 'Digestive'),
('K659', 'เยื่อบุช่องท้องอักเสบ', 'Peritonitis, unspecified', 'Digestive'),
('K590', 'ท้องผูก', 'Constipation', 'Digestive'),
('K920', 'อาเจียนเป็นเลือด', 'Haematemesis', 'Digestive'),
('K921', 'อุจจาระเป็นเลือด', 'Melaena', 'Digestive'),
-- Dental
('K029', 'ฟันผุ', 'Dental caries, unspecified', 'Dental'),
('K050', 'เหงือกอักเสบเฉียบพลัน', 'Acute gingivitis', 'Dental'),
('K0880', 'ปวดฟัน', 'Toothache', 'Dental'),
('K0888', 'ฟันโยก', 'Other specified disorders of teeth', 'Dental'),
('K011', 'ฟันคุด', 'Impacted teeth', 'Dental'),
('K120', 'แผลแอ็ฟทัส', 'Recurrent oral aphthae', 'Dental'),
('K121', 'แผลร้อนใน', 'Other forms of stomatitis', 'Dental'),
('K051', 'เหงือกอักเสบเรื้อรัง', 'Chronic gingivitis', 'Dental'),
('K140', 'ลิ้นอักเสบ', 'Glossitis', 'Dental'),
('K060', 'เหงือกร่น', 'Gingival recession', 'Dental'),
('K032', 'ฟันสึกกร่อน', 'Erosion of teeth', 'Dental'),
-- Circulatory
('I10', 'ความดันโลหิตสูงไม่ทราบสาเหตุ', 'Essential (primary) hypertension', 'Circulatory'),
('I959', 'ความดันโลหิตต่ำ', 'Hypotension, unspecified', 'Circulatory'),
('I738', 'ชาปลายมือปลายเท้า', 'Other specified peripheral vascular diseases', 'Circulatory'),
-- Skin
('L080', 'ผิวหนังเป็นหนอง', 'Pyoderma', 'Skin'),
('L270', 'ผื่นทั่วตัวจากแพ้ยา', 'Generalized skin eruption due to drugs', 'Skin'),
('L271', 'ผื่นเฉพาะที่จากแพ้ยา', 'Localized skin eruption due to drugs', 'Skin'),
('L290', 'คันทวารหนัก', 'Pruritus ani', 'Skin'),
('L293', 'คันถุงอัณฑะ', 'Anogenital pruritus, unspecified', 'Skin'),
('L309', 'ผิวอักเสบ', 'Dermatitis, unspecified', 'Skin'),
('L500', 'ลมพิษจากภูมิแพ้', 'Allergic urticaria', 'Skin'),
('L509', 'ลมพิษไม่ระบุ', 'Urticaria, unspecified', 'Skin'),
('L600', 'เล็บขบ', 'Ingrowing nail', 'Skin'),
('L84', 'ตาปลา', 'Corns and callosities', 'Skin'),
-- Injuries / Trauma
('S109', 'แผลถลอกที่คอ', 'Superficial injury of neck', 'Injury'),
('S308', 'แผลถลอกที่ท้อง/หลังล่าง', 'Superficial injury of abdomen/lower back', 'Injury'),
('S118', 'แผลเปิดที่คอ', 'Open wound of neck', 'Injury'),
('S310', 'แผลเปิดที่ท้อง/หลังล่าง', 'Open wound of lower back/pelvis', 'Injury'),
('S312', 'แผลเปิดที่องคชาติ', 'Open wound of penis', 'Injury'),
('S313', 'แผลเปิดที่อัณฑะ', 'Open wound of scrotum and testes', 'Injury'),
('S410', 'แผลเปิดที่ไหล่', 'Open wound of shoulder', 'Injury'),
('S411', 'แผลเปิดที่ต้นแขน', 'Open wound of upper arm', 'Injury'),
('S510', 'แผลเปิดที่ข้อศอก', 'Open wound of elbow', 'Injury'),
('S519', 'แผลเปิดที่แขนท่อนปลาย', 'Open wound of forearm', 'Injury'),
('S610', 'แผลเปิดที่นิ้วมือไม่รวมเล็บ', 'Open wound of finger(s) without nail damage', 'Injury'),
('S611', 'แผลเปิดที่นิ้วมือรวมเล็บ', 'Open wound of finger(s) with nail damage', 'Injury'),
('S618', 'แผลเปิดที่ข้อมือ/มือ', 'Open wound of wrist and hand', 'Injury'),
('S710', 'แผลเปิดที่สะโพก', 'Open wound of hip', 'Injury'),
('S711', 'แผลเปิดที่ต้นขา', 'Open wound of thigh', 'Injury'),
('S810', 'แผลเปิดที่เข่า', 'Open wound of knee', 'Injury'),
('S819', 'แผลเปิดที่ขาท่อนล่าง', 'Open wound of lower leg', 'Injury'),
('S910', 'แผลเปิดที่ข้อเท้า', 'Open wound of ankle', 'Injury'),
-- Burns
('T150', 'สิ่งแปลกปลอมในกระจกตา', 'Foreign body in cornea', 'Injury'),
('T151', 'สิ่งแปลกปลอมในถุงเยื่อตา', 'Foreign body in conjunctival sac', 'Injury'),
('T16', 'สิ่งแปลกปลอมในหู', 'Foreign body in ear', 'Injury'),
('T171', 'สิ่งแปลกปลอมในจมูก', 'Foreign body in nostril', 'Injury'),
('T180', 'สิ่งแปลกปลอมในปาก', 'Foreign body in mouth', 'Injury'),
-- Envenomation
('T6301', 'พิษงูเห่า งูจงอาง (ประสาท)', 'Snake venom, neurotoxin', 'Injury'),
('T6300', 'พิษงูแมวเซา งูเขียวหางไหม้ (เลือด)', 'Snake venom, haematotoxin', 'Injury'),
('T6309', 'พิษงูไม่ทราบชนิด', 'Snake venom, unspecified', 'Injury'),
('T632', 'พิษแมงป่อง', 'Venom of scorpion', 'Injury'),
('T634', 'พิษแตน ตะขาบ', 'Venom of other arthropods', 'Injury'),
('T639', 'สัตว์พิษไม่ทราบชนิด', 'Toxic effect of unspecified venomous animal', 'Injury'),
-- Post-operative / Wound care
('T814', 'แผลผ่าตัดติดเชื้อ', 'Infection following a procedure', 'Injury'),
('T793', 'แผลที่เกิดจากการบาดเจ็บติดเชื้อ', 'Post-traumatic wound infection', 'Injury'),
-- Administrative / Z-codes
('Z480', 'มาตัดไหม / มาทำแผล', 'Attention to surgical dressings and sutures', 'Administrative'),
('Z758', 'ส่งตัวไปตรวจทางห้องปฏิบัติการ', 'Other problems related to medical facilities', 'Administrative'),
('Z768', 'ส่งตัวไปตามแพทย์นัด / ขอยาให้คนอื่น', 'Persons encountering health services in other circumstances', 'Administrative'),
('Z013', 'ขอวัดความดันโลหิต', 'Examination of blood pressure', 'Administrative'),
('Z235', 'ฉีดวัคซีนบาดทะยัก (TT, DT) กระตุ้น', 'Need for immunization against tetanus alone', 'Administrative'),
('Z251', 'ฉีดวัคซีนไข้หวัดใหญ่', 'Need for immunization against influenza', 'Administrative'),
('Z000', 'ตรวจร่างกายทั่วไป', 'General medical examination', 'Administrative'),
('Z017', 'ตรวจเลือดหรือปัสสาวะ', 'Laboratory examination', 'Administrative'),
('Z012', 'ตรวจฟัน', 'Dental examination', 'Administrative'),
('Z027', 'ตรวจและออกใบรับรองแพทย์', 'Issue of medical certificate', 'Administrative'),
('Z131', 'ตรวจคัดกรองเบาหวาน', 'Special screening examination for diabetes mellitus', 'Administrative'),
('Z304', 'รับถุงยาง/ยาคุม/ปรึกษาคุมกำเนิด', 'Surveillance of contraceptive drugs', 'Administrative')
ON CONFLICT (code) DO UPDATE SET
    description_th = EXCLUDED.description_th,
    description_en = EXCLUDED.description_en,
    category = EXCLUDED.category;

-- ============================================================
-- End of 012_icd10_seed_from_clinic
-- ============================================================
